#!/usr/bin/env python3
"""Extracts Kurisu's system prompts from the original RealAmadeus C# source.

Usage: python3 scripts/extract-prompts.py /path/to/RealAmadeus

Writes web/src/ai/prompts.generated.ts with the prompts verbatim (C# verbatim
strings: "" -> "). Re-run when the upstream persona changes.
"""
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "web" / "src" / "ai" / "prompts.generated.ts"

CONSTS = {
    "KURISU_SYSTEM_PROMPT": "FULL_JA",
    "KURISU_SYSTEM_PROMPT_SHORT": "ja",
    "KURISU_SYSTEM_PROMPT_SHORT_EN": "en",
    "KURISU_SYSTEM_PROMPT_SHORT_ZH": "zh",
    "KURISU_SYSTEM_PROMPT_SHORT_KO": "ko",
    "KURISU_SYSTEM_PROMPT_SHORT_ES": "es",
    "KURISU_SYSTEM_PROMPT_SHORT_FR": "fr",
    "KURISU_SYSTEM_PROMPT_SHORT_DE": "de",
    "KURISU_SYSTEM_PROMPT_SHORT_RU": "ru",
}


def verbatim_strings(text: str):
    """Yields (start_index, value) for every C# @"..." literal."""
    i = 0
    while True:
        i = text.find('@"', i)
        if i < 0:
            return
        j = i + 2
        buf = []
        while j < len(text):
            if text[j] == '"':
                if j + 1 < len(text) and text[j + 1] == '"':
                    buf.append('"')
                    j += 2
                    continue
                break
            buf.append(text[j])
            j += 1
        yield i, "".join(buf).replace("\r\n", "\n")
        i = j + 1


def main():
    if len(sys.argv) != 2:
        print(__doc__)
        sys.exit(1)
    src = Path(sys.argv[1]) / "Assets" / "Scripts" / "AmadeusChatController.cs"
    text = src.read_text(encoding="utf-8")

    prompts = {}
    literals = list(verbatim_strings(text))
    for const, key in CONSTS.items():
        m = re.search(r"const string " + re.escape(const) + r"\s*=\s*\n?\s*@\"", text)
        if not m:
            raise SystemExit(f"{const} not found")
        start = m.end() - 2
        value = next(v for pos, v in literals if pos == start)
        prompts[key] = value

    ws = text[text.index("private string GetWebSearchContext()"):]
    ws_literals = [v for _, v in verbatim_strings(ws)][:2]
    web_search = {"ja": ws_literals[0], "en": ws_literals[1]}

    full_ja = prompts.pop("FULL_JA")
    lines = [
        "// Generated by scripts/extract-prompts.py from RealAmadeus (DSUV / ELVELT, CC BY-NC 4.0).",
        "// Do not edit by hand.",
        "",
        f"export const KURISU_PROMPT_FULL_JA = {json.dumps(full_ja, ensure_ascii=False)};",
        "",
        "export const KURISU_PROMPTS_SHORT: Record<string, string> = {",
    ]
    for key, value in prompts.items():
        lines.append(f"  {key}: {json.dumps(value, ensure_ascii=False)},")
    lines += [
        "};",
        "",
        "export const WEB_SEARCH_CONTEXT: Record<'ja' | 'en', string> = {",
        f"  ja: {json.dumps(web_search['ja'], ensure_ascii=False)},",
        f"  en: {json.dumps(web_search['en'], ensure_ascii=False)},",
        "};",
        "",
    ]
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}: {', '.join(prompts)} + full ja + web search")


if __name__ == "__main__":
    main()
